// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtI_FK85mVM4J014sh7quVgvj1dtTcZb8',
    appId: '1:747328417248:web:650a268e982dbf722ccf85',
    messagingSenderId: '747328417248',
    projectId: 'japaneseapp-72ffa',
    authDomain: 'japaneseapp-72ffa.firebaseapp.com',
    databaseURL: 'https://japaneseapp-72ffa-default-rtdb.firebaseio.com',
    storageBucket: 'japaneseapp-72ffa.firebasestorage.app',
    measurementId: 'G-JNL5TC3948',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCndlTH_dMKODe_10Yjd6oG73Qs7PIN9Ns',
    appId: '1:747328417248:android:d204db7b40dade7c2ccf85',
    messagingSenderId: '747328417248',
    projectId: 'japaneseapp-72ffa',
    databaseURL: 'https://japaneseapp-72ffa-default-rtdb.firebaseio.com',
    storageBucket: 'japaneseapp-72ffa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANTdXwjI62khNheMTU7JXBv_OqNvlOWcM',
    appId: '1:747328417248:ios:b2fc038455d1f76c2ccf85',
    messagingSenderId: '747328417248',
    projectId: 'japaneseapp-72ffa',
    databaseURL: 'https://japaneseapp-72ffa-default-rtdb.firebaseio.com',
    storageBucket: 'japaneseapp-72ffa.firebasestorage.app',
    iosBundleId: 'com.example.kanjiSummoner',
  );
}
